name: MDP unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Installing dependencies
      run: |
        pip install -r requirements.txt
    - name: Running Unit tests
      run: |
        python **/*.test.py
