name: MDP unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Installing dependencies
      run: |
        sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
        pip install -r requirements.txt
    - name: Running Unit tests
      run: |
        python **/*.test.py
